---
- 
  name: Installing Docker CE
  hosts: tag_Name_minions
  gather_facts: False
  become: yes
  pre_tasks:
    - name: Install python for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:
  tasks:
    - 
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present
    - 
      apt_repository: 
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' 
        state: present 
        filename: 'docker'
        update_cache: 'yes'
    - 
      apt: 
        name: 'docker-ce'

- 
  name: Initialize Swarm Master
  hosts: tag_Name_minions[0]
  gather_facts: yes
  become: true
  tasks:
    - 
      command: "docker swarm init --advertise-addr {{inventory_hostname}}"
    - 
      command: "docker swarm join-token -q worker"
      register: swarm_token
    - 
      set_fact: swarmtoken="{{swarm_token.stdout}}"
    - 
      debug:
        msg: "System {{inventory_hostname}} has swarm token {{swarm_token.stdout}}"  
  
- 
  name: Join Swarm Nodes
  hosts: tag_Name_minions[1:]
  gather_facts: yes
  become: true
  tasks:
    - 
      debug:
        msg: "Perivious step swarm token {{hostvars[groups['tag_Name_minions'][0]].swarmtoken}} and inventory hostname {{hostvars[groups['tag_Name_minions'][0]].inventory_hostname}}"
    - 
      command: "docker swarm join --advertise-addr {{inventory_hostname}} --token {{hostvars[groups['tag_Name_minions'][0]].swarmtoken}} {{hostvars[groups['tag_Name_minions'][0]].inventory_hostname}}:2377"

- 
  name: Copy docker compose file
  hosts: tag_Name_minions[0]
  gather_facts: yes
  become: true
  tasks:
    -
      file:
        path: ~/compose
        state: directory
    -
      copy:
          src: ~/compose/docker-dev-stack.yml
          dest: ~/compose/docker-dev-stack.yml
    -
      copy:
          src: ~/compose/docker-test-stack.yml
          dest: ~/compose/docker-test-stack.yml

- 
  name: Start docker stack for dev and test
  hosts: tag_Name_minions[0]
  gather_facts: yes
  become: true
  tasks:
    -
      args:
        chdir: ~/compose
      command: "docker stack deploy -c docker-dev-stack.yml votingapp_dev"
    -
      args:
        chdir: ~/compose
      command: "docker stack deploy -c docker-test-stack.yml votingapp_test"