version: "3"
services:
    nginx:
      image: yrameshrao/nginx:latest
      ports:
        - "10000:80"
      networks:
        - developer

    healthcheck:
      image: yrameshrao/dockerhealthcheck:latest
      networks:
        - developer

    redis:
      image: redis:alpine
      ports:
        - "6379"
      networks:
        - developer
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
    
    db:
      image: postgres:9.4
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - developer
    
    vote:
      image: dockersamples/examplevotingapp_vote:before
      networks:
        - developer
      depends_on:
        - redis
      deploy:
        replicas: 2
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure

    result:
      image: dockersamples/examplevotingapp_result:before
      networks:
        - developer
      depends_on:
        - db
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
    
    worker:
      image:  dockersamples/examplevotingapp_worker
      networks:
        - developer
    
    visualizer:
      image: dockersamples/visualizer
      stop_grace_period: 1m30s
      deploy:
        placement:
          constraints:
            - node.role == manager
      networks:
        - developer
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  developer:

volumes:
  db-data:      
          

